let studentData = [
  {
    name: "irsahd",
    branch: "Hitech City",
    leadsource: "JustDail",
    counsellor: "kavya",
    companyname: "teks",
    course: "java",
    admissionDate: "25-01-2023",
  },
  {
    name: "balu",
    branch: "Dilshuknagar",
    leadsource: "IndiaMart",
    counsellor: "kavya",
    companyname: "kapil",
    course: "java",
    admissionDate: "25-02-2023",
  },
  {
    name: "bhavita",
    branch: "Dilshuknagar",
    leadsource: "JustDail",
    counsellor: "kavya",
    companyname: "teks",
    course: "java",
    admissionDate: "25-03-2023",
  },
  {
    name: "irshad",
    branch: "kukatpally",
    leadsource: "IndiaMart",
    counsellor: "kavya",
    companyname: "kapil",
    course: "java",
    admissionDate: "25-04-2023",
  },
  {
    name: "srikanth",
    branch: "ameerpet",
    leadsource: "Naukri",
    counsellor: "kavya",
    companyname: "teks",
    course: "java",
    admissionDate: "25-05-2023",
  },
  {
    name: "kavya",
    branch: "ameerpet",
    leadsource: "JustDail",
    counsellor: "kavya",
    companyname: "kapil",
    course: "python",
    admissionDate: "25-06-2023",
  },
  {
    name: "shasi",
    branch: "",
    leadsource: "Naukri",
    counsellor: "kavya",
    companyname: "teks",
    course: "java",
    admissionDate: "25-07-2023",
  },
  {
    name: "preme",
    branch: "Hitech City",
    leadsource: "JustDail",
    counsellor: "kavya",
    companyname: "kapil",
    course: "java",
    admissionDate: "25-08-2023",
  },
  {
    name: "bhaskar",
    branch: "Hitech City",
    leadsource: "JustDail",
    counsellor: "kavya",
    companyname: "teks",
    course: "python",
    admissionDate: "25-09-2023",
  },
  {
    name: "suma",
    branch: "Hitech City",
    leadsource: "PhonePe",
    counsellor: "kavya",
    companyname: "kapil",
    course: "python",
    admissionDate: "25-10-2023",
  },
];
